name: olaclick
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+57

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #LANGUAGE - TRANSLATE
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0
  location: ^2.3.5
  geolocator: ^7.6.0
  money2: ^2.0.1-nullsafety.3
  
  #FIREBASE ANDROID
  firebase_core:
  #firebase_analytics:
  firebase_messaging:
  firebase_crashlytics:

  #PRINTER BLUETOOTH - ANDROID
  esc_pos_bluetooth: ^0.2.8
  flutter_blue:
  flutter_bluetooth_basic: ^0.1.5
  #esc_pos_printer: ^2.0.0

  #PRINTER IOS
  flutter_ble_lib: ^2.3.2

  #APPSFLYER - MKT - ANDROID
  appsflyer_sdk: ^6.5.2+1

  #RESOLVE PROBLEM WITH firebase
  firebase_messaging_platform_interface: 3.1.6  

  #UPLOAD IMAGE
  flutter_image_compress: ^1.1.0
  open_filex: ^3.4.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.9
  android_intent: ^2.0.2
  http: ^0.13.3

  permission_handler: ^8.1.6
#  sentry_flutter:
  shared_preferences:
  #fonts
  cupertino_icons: ^1.0.2
  #validation
  diacritic: ^0.1.3
  flutter_html:
  path_provider:
  
module:
    androidX: true # Add this line.
  
dev_dependencies:
  flutter_launcher_icons: null

  flutter_native_splash: null
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0090DF"
  image: assets/splash.jpg
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
